# Generated by rspec-sinatra. (2016-06-27 12:22:38 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', 'app.rb')

require 'capybara'
require 'capybara/rspec'
require 'rspec'
require 'database_cleaner'
require './models/init'
require_relative './helpers/user_helpers'
require_relative './helpers/space_helpers'
require_relative './helpers/booking_helpers'
require_relative './helpers/pony_helpers'

Capybara.app = App

RSpec.configure do |config|
  config.include Capybara::DSL
  config.include UsersHelper
  config.include SpaceHelper
  config.include BookingHelper
  config.include Rack::Test::Methods

  config.before(:suite) do
    DatabaseCleaner.strategy = :truncation
    DatabaseCleaner.clean_with(:truncation, reset_ids: true)
  end

  config.before(:each) do
    DatabaseCleaner.start
    dont_send_email
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end

  config.expect_with :rspec do |expectations|

    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|

    mocks.verify_partial_doubles = true
  end

end
